version: 0.2

phases:
  install:
    commands:
      - npm install -g n
      - n 24.18.0
      - hash -r
      - node --version
      - npm --version
      - npm ci

  build:
    commands:
      - hash -r
      - node --version
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'