version: 0.2

phases:
  install:
    commands:
      - n --version
      - n 24.18.0
      - hash -r
      - node --version
      - npm --version
      - npm ci

  build:
    commands:
      - hash -r
      - node --version
      - npm run build

  post_build:
    commands:
      - zip -r dist/webapp.zip dist

artifacts:
  base-directory: dist
  files:
    - webapp.zip